name: CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - "main"
env:
  # using a dummy secret key
  DJANGO_SETTINGS_MODULE: rdwatch.server.settings
  RDWATCH_SECRET_KEY: ff07f533a59fed1349a4fc49941d02ff22514f6dbf6086a44ea0c0a8952e8644
  RDWATCH_POSTGRESQL_URI: postgresql://rdwatch:ff07f533a59fed1349a4fc49941d02ff22514f6dbf6086a44ea0c0a8952e8644@localhost:5432/rdwatch
  RDWATCH_REDIS_URI: redis://rdwatch:ff07f533a59fed1349a4fc49941d02ff22514f6dbf6086a44ea0c0a8952e8644@localhost:6379/rdwatch
  RDWATCH_DJANGO_DEBUG: 0
jobs:
  lint-python:
    strategy:
      fail-fast: false
      matrix:
        linter: [black, flake8, isort]
    name: Lint [${{ matrix.linter }}]
    runs-on: ubuntu-22.04
    steps:
      - name: Install system dependencies
        run: apt-fast install --no-install-recommends --yes
          libgdal30
          libproj22
          python3-cachecontrol
          python3-dev
          python3-poetry
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "django/poetry.lock"
      - name: Install packages
        run: poetry install
        working-directory: django
      - name: Run ${{ matrix.linter }}
        run: poetry run task lint:${{ matrix.linter }}
        working-directory: django
  lint-node:
    strategy:
      fail-fast: false
      matrix:
        linter: [prettier, eslint, stylelint, typescript]
    name: Lint [${{ matrix.linter }}]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: vue/package-lock.json
      - name: Install packages
        run: npm ci
        working-directory: vue
      - name: Run ${{ matrix.linter }}
        run: npm run lint:${{ matrix.linter }}
        working-directory: vue
  test-django:
    name: Test [django]
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: ghcr.io/resonantgeodata/rd-watch/postgresql:latest
        env:
          POSTGRES_PASSWORD: ${{ env.RDWATCH_SECRET_KEY }}
      redis:
        image: ghcr.io/resonantgeodata/rd-watch/redis:latest
        env:
          RDWATCH_SECRET_KEY: ${{ env.RDWATCH_SECRET_KEY }}
    steps:
      - name: Install system dependencies
        run: apt-fast install --no-install-recommends --yes
          libgdal30
          libproj22
          python3-cachecontrol
          python3-dev
          python3-poetry
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "django/poetry.lock"
      - name: Install packages
        run: poetry install
        working-directory: django
      - name: Run tests
        run: poetry run django-admin test
        working-directory: django
  test-django-makemigrations:
    name: Test [django makemigrations]
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: ghcr.io/resonantgeodata/rd-watch/postgresql:latest
        env:
          POSTGRES_PASSWORD: ${{ env.RDWATCH_SECRET_KEY }}
      redis:
        image: ghcr.io/resonantgeodata/rd-watch/redis:latest
        env:
          RDWATCH_SECRET_KEY: ${{ env.RDWATCH_SECRET_KEY }}
    steps:
      - name: Install system dependencies
        run: apt-fast install --no-install-recommends --yes
          libgdal30
          libproj22
          python3-cachecontrol
          python3-dev
          python3-poetry
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
          cache-dependency-path: "django/poetry.lock"
      - name: Install packages
        run: poetry install
        working-directory: django
      - name: Check for up-to-date migrations
        run: poetry run django-admin makemigrations --dry-run --check
        working-directory: django
  test-vue:
    name: Test [vue]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: vue/package-lock.json
      - name: Install packages
        run: npm ci
        working-directory: vue
      - name: Run tests
        run: npm run test
        working-directory: vue
